# Generated by Django 3.0.5 on 2020-04-28 05:34

import adtaa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_num', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('meeting_day', models.CharField(choices=[('MW', 'Monday Wednesday'), ('TH', 'Tuesday Thursday')], max_length=2)),
                ('meeting_time', models.CharField(choices=[('8:00AM', '8:00AM-9:15AM'), ('9:25AM', '9:25AM-10:40AM'), ('10:50AM', '10:50AM-12:05PM'), ('12:15PM', '12:15PM-1:30PM'), ('1:40PM', '1:40PM-2:55PM'), ('3:05PM', '3:05PM-4:20PM'), ('4:30PM', '4:30PM-5:45PM'), ('5:55PM', '5:55PM-7:10PM')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_num', models.CharField(max_length=4)),
                ('title', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('meeting_day', models.CharField(choices=[('MW', 'Monday Wednesday'), ('TH', 'Tuesday Thursday')], max_length=2)),
                ('meeting_time', models.CharField(choices=[('8:00AM', '8:00AM-9:15AM'), ('9:25AM', '9:25AM-10:40AM'), ('10:50AM', '10:50AM-12:05PM'), ('12:15PM', '12:15PM-1:30PM'), ('1:40PM', '1:40PM-2:55PM'), ('3:05PM', '3:05PM-4:20PM'), ('4:30PM', '4:30PM-5:45PM'), ('5:55PM', '5:55PM-7:10PM')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('last_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('class_load', models.IntegerField(validators=[adtaa.models.validate_1to4])),
                ('areas', models.ManyToManyField(to='adtaa.Area')),
            ],
        ),
    ]
